CREATE TABLE schedule
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 식별자',
    name VARCHAR(100) NOT NULL COMMENT '작성자',
    password VARCHAR(100) NOT NULL COMMENT '비밀번호',
    title VARCHAR(100) NOT NULL COMMENT '제목',
    contents TEXT COMMENT '내용',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);